### ISSUE TITLE
 Invalid or unsupported zip format

### ISSUE THREAD

**Issue by coronin** [sueszli/notionBackup#4] opened 2023-10-26 20:00 UTC
/notionBackup/node_modules/adm-zip/zipFile.js:101
                if (!~endOffset) throw new Error(Utils.Errors.INVALID_FORMAT);
                                       ^
        Error: Invalid or unsupported zip format. No END header found

I have error shown above, when  npx ts-node notionbackup ./demo/blog.zip
nodejs@20.9.0, npm@10.2.1

**Comment by sueszli** [comment] 2023-10-26 20:13
Hi - May I ask for more details for reproducability?

Thanks,
Yahya

**Comment by sueszli** [comment] 2023-11-20 18:32
@coronin update: should be fixed now!

**Comment by sueszli** [comment] 2023-11-20 18:32
let me know if it worked and i'll close the issue

**Comment by santur90** [comment] 2023-11-21 18:27
I met the same issue

**Comment by sueszli** [comment] 2023-11-21 18:28
@santur90 what are the file properties?

**Comment by santur90** [comment] 2023-11-21 18:32
$ bun run notionbackup.ts ./demo/blog.zip
    _   __      __  _                ____             __
   / | / /___  / /_(_)___  ____     / __ )____ ______/ /____  ______
  /  |/ / __ \/ __/ / __ \/ __ \   / __  / __ `/ ___/ //_/ / / / __ \
 / /|  / /_/ / /_/ / /_/ / / / /  / /_/ / /_/ / /__/ ,< / /_/ / /_/ /
/_/ |_/\____/\__/_/\____/_/ /_/  /_____/\__,_/\___/_/|_|\__,_/ .___/
                                                            /_/
 96 |                 endStart = i + Utils.readBigUInt64LE(inBuffer, i + Utils.Constants.ZIP64SIZE) + Utils.Constants.ZIP64LEAD;
 97 |                 break;
 98 |             }
 99 |         }
100 |
101 |         if (!~endOffset) throw new Error(Utils.Errors.INVALID_FORMAT);
                                   ^
error: Invalid or unsupported zip format. No END header found
      at readMainHeader (.notionBackup/node_modules/adm-zip/zipFile.js:101:31)
      at new  (.notionBackup/node_modules/adm-zip/zipFile.js:19:8)
      at new  (.notionBackup/node_modules/adm-zip/adm-zip.js:62:17)
      at getUnzippedInputPath (.notionBackup/notionbackup.ts:34:16)
      at .notionBackup/notionbackup.ts:193:30
      at main (.notionBackup/notionbackup.ts:186:13)
      at .notionBackup/notionbackup.ts:205:0
      at processTicksAndRejections (:61:76)

**Comment by sueszli** [comment] 2023-11-21 18:39
Thanks for sharing the trace – May I ask you to share the zip with me for reproducability?

**Comment by santur90** [comment] 2023-11-21 18:40
that's your demo, still need it?

**Comment by sueszli** [comment] 2023-11-21 19:00
oh nevermind – just noticed.

okay this is odd. which operating system are you running? i honestly have no idea why "adm-zip" is crashing

**Comment by santur90** [comment] 2023-11-21 19:02
macOS Monterey

**Comment by sueszli** [comment] 2023-11-21 19:14
not much i can do: https://github.com/oven-sh/bun/issues/7248

seems to be a very recent bun bug that occured within the last 7 hours (my script worked flawlessly last night)

**Comment by santur90** [comment] 2023-11-21 19:25
got it, thanks!

**Comment by sueszli** [comment] 2023-11-29 14:18
@santur90 @coronin migrated to node

**Comment by sueszli** [comment] 2023-11-29 14:18
should be fixed now. closing the issue.

**Comment by sueszli** [comment] 2023-11-29 14:18
feel free to donate / leave a star

**Closed as completed by sueszli** 2023-11-29 14:18 UTC
